# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='active',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
