# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_slides_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='hash',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
