# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_slides_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
