# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_user_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('slider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Slides')),
            ],
        ),
    ]
