# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('src', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('src', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('speed', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('background', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slidemanager.Background')),
                ('photo', models.ManyToManyField(to='slidemanager.Photos')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slidemanager.MemberShip')),
            ],
        ),
        migrations.AddField(
            model_name='slides',
            name='user',
            field=models.ManyToManyField(to='slidemanager.User'),
        ),
    ]
