# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slidemanager', '0003_auto_20160921_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slidemanager.Background'),
        ),
    ]
